# Site specific settings
title: TEST
name: "Website name"
keywords: "Key, words, about, this, website"
baseurl: ""
url: "https://stealthyunic0rn.github.io"
description: "Learning through fire"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https

#### Under the hood stuff
markdown: kramdown

